[platformio]
src_dir = .
include_dir = .

[env:r4wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200
lib_deps =
    arduino-libraries/ArduinoBLE
    fastled/FastLED
    Arduino-IRremote/IRremote
lib_ignore = I2S
build_flags = -DFASTLED_NO_AUDIO
